### ISSUE TITLE
how to set the default language? 

### ISSUE THREAD

**Issue by gunstonej** [jupyterlab-contrib/jupyterlab_spellchecker#28]
hi there, 
great extension!
how do i change the default language? 
cheers

**Comment by krassowski** [comment]
Just to understand better, do you wish to restore the chosen language choice (as selected from the statusbar) between JupyterLab restarts and apply it to all the documents?

**Comment by gunstonej** [comment]
thanks for the quick response - 

i'd like to change the language to default to British English for all instances of JupyterLab moving forwards. 
ideally in in a way that i can write a simple script to do it quietly on other users machines. 

after some snooping i found this the jupyterlab settings section...

![image](https://user-images.githubusercontent.com/21370980/90399202-7e7a1b00-e092-11ea-9693-8f462f5432d2.png)

**Comment by gunstonej** [comment]
``

**Comment by gunstonej** [comment]
sorry - closed this by accident!

**Comment by krassowski** [comment]
The language is now saved by default based on the language chosen using the language picker, but you can also change it manually in the Settings → Advanced Settings Editor:

![Screenshot from 2021-02-26 15-20-29](https://user-images.githubusercontent.com/5832902/109318920-3bb9ac80-7846-11eb-97ab-43b8e1bee228.png)
