### ISSUE TITLE
How to add Spanish dictionary

### ISSUE THREAD

**Issue by Santivg** [jupyterlab-contrib/jupyterlab_spellchecker#29]
Hello, I want to know if there is a way of adding a Spanish dictionary and if is possible how can I do it?

**Comment by nthiery** [comment]
Looking forward to it! (for French in my case)

**Comment by dguioML** [comment]
hello excellent repo. I would like to know if you have advanced in this matter?

**Comment by krassowski** [comment]
The Spanish dictionary is already available in the latest version of this extension :)
